parameters:
  PublishRidAgnosticPackagesFromPlatform: ''
  isOfficialBuild: false
  logArtifactName: 'Logs-PrepareSignedArtifacts_Attempt$(System.JobAttempt)'
  bindings:
    isBindingsBuild: false
    scriptArgs: ''

jobs:
- template: /eng/common/templates-official/job/job.yml
  parameters:
    name: 'PrepareSignedArtifacts'
    displayName: 'Prepare Signed Artifacts'

    pool:
      name: Azure Pipelines
      image: macos-latest
      os: macOS

    # Double the default timeout.
    timeoutInMinutes: 240

    workspace:
      clean: all

    enableMicrobuild: true

    variables:
      - name: '_SignType'
        value: $[ coalesce(variables.OfficialSignType, 'real') ]
      - _BuildConfig: Release
      - _buildScript: ./build.sh
      - _generateScript: ./generate.sh

    steps:
    - script: >-
        $(_buildScript) -ci
        -publish
        -pack
        -configuration $(_BuildConfig)
        /p:PublishRidAgnosticPackagesFromPlatform=${{ parameters.PublishRidAgnosticPackagesFromPlatform }}
        /p:OfficialBuildId=$(Build.BuildNumber)
        /p:SignType=$(_SignType)
        /p:DotNetSignType=$(_SignType)
        /p:DotNetPublishUsingPipelines=true
        /bl:$(Build.SourcesDirectory)\prepare-artifacts.binlog
      displayName: Prepare tooling artifacts and upload to build

    - script: $(_generateScript) --configuration $(_BuildConfig) --platform MacOSX ${{ scriptArgs }}
      displayName: Generate MacOSX bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform iPhoneOS ${{ scriptArgs }}
      displayName: Generate iOS bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform iPhoneSimulator ${{ scriptArgs }}
      displayName: Generate iOSSimulator bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform AppleTVOS ${{ scriptArgs }}
      displayName: Generate tvOS bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform AppleTVSimulator ${{ scriptArgs }}
      displayName: Generate tvOSSimulator bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform iPhoneOS --maccatalyst ${{ scriptArgs }}
      displayName: Generate MacCatalyst bindings

    - script: >-
        $(_buildScript) -ci
        -publish
        -pack
        -configuration $(_BuildConfig)
        --projects ./GeneratedBindings/MacOSX/Swift.Bindings.MacOSX.Experimental.csproj;./GeneratedBindings/iPhoneOS/Swift.Bindings.iPhoneOS.Experimental.csproj;./GeneratedBindings/iPhoneSimulator/Swift.Bindings.iPhoneSimulator.Experimental.csproj;./GeneratedBindings/AppleTVOS/Swift.Bindings.AppleTVOS.Experimental.csproj;./GeneratedBindings/AppleTVSimulator/Swift.Bindings.AppleTVSimulator.Experimental.csproj;./GeneratedBindings/MacCatalyst/Swift.Bindings.MacCatalyst.Experimental.csproj
        /p:PublishRidAgnosticPackagesFromPlatform=${{ parameters.PublishRidAgnosticPackagesFromPlatform }}
        /p:OfficialBuildId=$(Build.BuildNumber)
        /p:SignType=$(_SignType)
        /p:DotNetSignType=$(_SignType)
        /p:DotNetPublishUsingPipelines=true
        /bl:$(Build.SourcesDirectory)\prepare-artifacts.binlog
      displayName: Prepare bindings artifacts and upload to build

    - task: CopyFiles@2
      displayName: Copy Files to $(Build.StagingDirectory)\BuildLogs
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          **/*.log
          **/*.binlog
        TargetFolder: '$(Build.StagingDirectory)\BuildLogs'
      continueOnError: true
      condition: succeededOrFailed()
