parameters:
  PublishRidAgnosticPackagesFromPlatform: ''
  isOfficialBuild: false
  logArtifactName: 'Logs-PrepareSignedArtifacts_Attempt$(System.JobAttempt)'
  scriptArgs: ''

jobs:
- template: /eng/common/templates-official/job/job.yml
  parameters:
    name: 'PrepareSignedArtifacts'
    displayName: 'Prepare Signed Artifacts'

    pool:
      name: Azure Pipelines
      image: macos-latest
      os: macOS

    # Double the default timeout.
    timeoutInMinutes: 240

    workspace:
      clean: all

    enableMicrobuild: true

    variables:
      - name: '_SignType'
        value: $[ coalesce(variables.OfficialSignType, 'real') ]
      - _BuildConfig: Release
      - _buildScript: ./build.sh
      - _generateScript: ./generate.sh

    steps:
    - script: >-
        $(_buildScript) -ci
        -publish
        -pack
        -configuration $(_BuildConfig)
        /p:PublishRidAgnosticPackagesFromPlatform=${{ parameters.PublishRidAgnosticPackagesFromPlatform }}
        /p:OfficialBuildId=$(Build.BuildNumber)
        /p:SignType=$(_SignType)
        /p:DotNetSignType=$(_SignType)
        /p:DotNetPublishUsingPipelines=true
        /bl:$(Build.SourcesDirectory)\prepare-artifacts.binlog
      displayName: Prepare tooling artifacts and upload to build

    - script: $(_generateScript) --configuration $(_BuildConfig) --platform MacOSX ${{ parameters.scriptArgs }}
      displayName: Generate MacOSX bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform iPhoneOS ${{ parameters.scriptArgs }}
      displayName: Generate iOS bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform iPhoneSimulator ${{ parameters.scriptArgs }}
      displayName: Generate iOSSimulator bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform AppleTVOS ${{ parameters.scriptArgs }}
      displayName: Generate tvOS bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform AppleTVSimulator ${{ parameters.scriptArgs }}
      displayName: Generate tvOSSimulator bindings
    - script: $(_generateScript) --configuration $(_BuildConfig) --platform MacCatalyst ${{ parameters.scriptArgs }}
      displayName: Generate MacCatalyst bindings

    - script: |
        for proj in artifacts/MacOSX/*.csproj artifacts/iPhoneOS/*.csproj artifacts/iPhoneSimulator/*.csproj artifacts/AppleTVOS/*.csproj artifacts/AppleTVSimulator/*.csproj artifacts/MacCatalyst/*.csproj; do
          $(_buildScript) -ci \
          -publish \
          -pack \
          -configuration $(_BuildConfig) \
          --projects "$(pwd)/$proj" \
          /p:PublishRidAgnosticPackagesFromPlatform=${{ parameters.PublishRidAgnosticPackagesFromPlatform }} \
          /p:OfficialBuildId=$(Build.BuildNumber) \
          /p:SignType=$(_SignType) \
          /p:DotNetSignType=$(_SignType) \
          /p:DotNetPublishUsingPipelines=true \
          /bl:$(Build.SourcesDirectory)\prepare-artifacts.binlog
        done
      displayName: Prepare bindings artifacts and upload to build

    - task: CopyFiles@2
      displayName: Copy Files to $(Build.StagingDirectory)\BuildLogs
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          **/*.log
          **/*.binlog
        TargetFolder: '$(Build.StagingDirectory)\BuildLogs'
      continueOnError: true
      condition: succeededOrFailed()
