#ifndef _MONOSHIM_METADATA_CLASS_INTERNALS_H
#define _MONOSHIM_METADATA_CLASS_INTERNALS_H

enum {
    MONO_WRAPPER_NONE = 0,
    MONO_WRAPPER_DYNAMIC_METHOD = 1,
    MONO_WRAPPER_NUM = MONO_WRAPPER_DYNAMIC_METHOD + 1, // keep updated
} MonoWrapperType;

#endif
