#ifndef _MONOSHIM_METADATA_METADATA_TYPES_H
#define _MONOSHIM_METADATA_METADATA_TYPES_H


typedef enum {
	MONO_EXCEPTION_CLAUSE_NONE,
	MONO_EXCEPTION_CLAUSE_FILTER,
	MONO_EXCEPTION_CLAUSE_FINALLY,
	MONO_EXCEPTION_CLAUSE_FAULT = 4
} MonoExceptionEnum;

#endif
