//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SwiftInterface.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SwiftInterfaceParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
// [System.CLSCompliant(false)]
public interface ISwiftInterfaceListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.swiftinterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwiftinterface([NotNull] SwiftInterfaceParser.SwiftinterfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.swiftinterface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwiftinterface([NotNull] SwiftInterfaceParser.SwiftinterfaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SwiftInterfaceParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SwiftInterfaceParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] SwiftInterfaceParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] SwiftInterfaceParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] SwiftInterfaceParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] SwiftInterfaceParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.nominal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNominal_declaration([NotNull] SwiftInterfaceParser.Nominal_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.nominal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNominal_declaration([NotNull] SwiftInterfaceParser.Nominal_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_statement([NotNull] SwiftInterfaceParser.Import_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_statement([NotNull] SwiftInterfaceParser.Import_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.import_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_kind([NotNull] SwiftInterfaceParser.Import_kindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.import_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_kind([NotNull] SwiftInterfaceParser.Import_kindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.import_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_path([NotNull] SwiftInterfaceParser.Import_pathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.import_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_path([NotNull] SwiftInterfaceParser.Import_pathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.import_path_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_path_identifier([NotNull] SwiftInterfaceParser.Import_path_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.import_path_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_path_identifier([NotNull] SwiftInterfaceParser.Import_path_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_declaration([NotNull] SwiftInterfaceParser.Variable_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_declaration([NotNull] SwiftInterfaceParser.Variable_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.variable_declaration_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_declaration_head([NotNull] SwiftInterfaceParser.Variable_declaration_headContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.variable_declaration_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_declaration_head([NotNull] SwiftInterfaceParser.Variable_declaration_headContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.variable_declaration_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_declaration_tail([NotNull] SwiftInterfaceParser.Variable_declaration_tailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.variable_declaration_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_declaration_tail([NotNull] SwiftInterfaceParser.Variable_declaration_tailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.variable_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_name([NotNull] SwiftInterfaceParser.Variable_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.variable_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_name([NotNull] SwiftInterfaceParser.Variable_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.var_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_clause([NotNull] SwiftInterfaceParser.Var_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.var_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_clause([NotNull] SwiftInterfaceParser.Var_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.let_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLet_clause([NotNull] SwiftInterfaceParser.Let_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.let_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLet_clause([NotNull] SwiftInterfaceParser.Let_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.getter_setter_keyword_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetter_setter_keyword_block([NotNull] SwiftInterfaceParser.Getter_setter_keyword_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.getter_setter_keyword_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetter_setter_keyword_block([NotNull] SwiftInterfaceParser.Getter_setter_keyword_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.getter_keyword_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetter_keyword_clause([NotNull] SwiftInterfaceParser.Getter_keyword_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.getter_keyword_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetter_keyword_clause([NotNull] SwiftInterfaceParser.Getter_keyword_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.setter_keyword_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetter_keyword_clause([NotNull] SwiftInterfaceParser.Setter_keyword_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.setter_keyword_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetter_keyword_clause([NotNull] SwiftInterfaceParser.Setter_keyword_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.new_value_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNew_value_name([NotNull] SwiftInterfaceParser.New_value_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.new_value_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNew_value_name([NotNull] SwiftInterfaceParser.New_value_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.typealias_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypealias_declaration([NotNull] SwiftInterfaceParser.Typealias_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.typealias_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypealias_declaration([NotNull] SwiftInterfaceParser.Typealias_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.typealias_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypealias_name([NotNull] SwiftInterfaceParser.Typealias_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.typealias_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypealias_name([NotNull] SwiftInterfaceParser.Typealias_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.typealias_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypealias_assignment([NotNull] SwiftInterfaceParser.Typealias_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.typealias_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypealias_assignment([NotNull] SwiftInterfaceParser.Typealias_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.enum_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_declaration([NotNull] SwiftInterfaceParser.Enum_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.enum_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_declaration([NotNull] SwiftInterfaceParser.Enum_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_style_enum([NotNull] SwiftInterfaceParser.Union_style_enumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_style_enum([NotNull] SwiftInterfaceParser.Union_style_enumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_style_enum_members([NotNull] SwiftInterfaceParser.Union_style_enum_membersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_style_enum_members([NotNull] SwiftInterfaceParser.Union_style_enum_membersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_style_enum_member([NotNull] SwiftInterfaceParser.Union_style_enum_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_style_enum_member([NotNull] SwiftInterfaceParser.Union_style_enum_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_case_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_style_enum_case_clause([NotNull] SwiftInterfaceParser.Union_style_enum_case_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_case_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_style_enum_case_clause([NotNull] SwiftInterfaceParser.Union_style_enum_case_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_case_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_style_enum_case_list([NotNull] SwiftInterfaceParser.Union_style_enum_case_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_case_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_style_enum_case_list([NotNull] SwiftInterfaceParser.Union_style_enum_case_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_style_enum_case([NotNull] SwiftInterfaceParser.Union_style_enum_caseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.union_style_enum_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_style_enum_case([NotNull] SwiftInterfaceParser.Union_style_enum_caseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.enum_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_name([NotNull] SwiftInterfaceParser.Enum_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.enum_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_name([NotNull] SwiftInterfaceParser.Enum_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.enum_case_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_case_name([NotNull] SwiftInterfaceParser.Enum_case_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.enum_case_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_case_name([NotNull] SwiftInterfaceParser.Enum_case_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_style_enum([NotNull] SwiftInterfaceParser.Raw_value_style_enumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_style_enum([NotNull] SwiftInterfaceParser.Raw_value_style_enumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_style_enum_members([NotNull] SwiftInterfaceParser.Raw_value_style_enum_membersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_style_enum_members([NotNull] SwiftInterfaceParser.Raw_value_style_enum_membersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_style_enum_member([NotNull] SwiftInterfaceParser.Raw_value_style_enum_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_style_enum_member([NotNull] SwiftInterfaceParser.Raw_value_style_enum_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_case_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_style_enum_case_clause([NotNull] SwiftInterfaceParser.Raw_value_style_enum_case_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_case_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_style_enum_case_clause([NotNull] SwiftInterfaceParser.Raw_value_style_enum_case_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_case_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_style_enum_case_list([NotNull] SwiftInterfaceParser.Raw_value_style_enum_case_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_case_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_style_enum_case_list([NotNull] SwiftInterfaceParser.Raw_value_style_enum_case_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_style_enum_case([NotNull] SwiftInterfaceParser.Raw_value_style_enum_caseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_style_enum_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_style_enum_case([NotNull] SwiftInterfaceParser.Raw_value_style_enum_caseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_assignment([NotNull] SwiftInterfaceParser.Raw_value_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_assignment([NotNull] SwiftInterfaceParser.Raw_value_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_value_literal([NotNull] SwiftInterfaceParser.Raw_value_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.raw_value_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_value_literal([NotNull] SwiftInterfaceParser.Raw_value_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declaration([NotNull] SwiftInterfaceParser.Struct_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declaration([NotNull] SwiftInterfaceParser.Struct_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.struct_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_name([NotNull] SwiftInterfaceParser.Struct_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.struct_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_name([NotNull] SwiftInterfaceParser.Struct_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.struct_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_body([NotNull] SwiftInterfaceParser.Struct_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.struct_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_body([NotNull] SwiftInterfaceParser.Struct_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.struct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_member([NotNull] SwiftInterfaceParser.Struct_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.struct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_member([NotNull] SwiftInterfaceParser.Struct_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.class_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_declaration([NotNull] SwiftInterfaceParser.Class_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.class_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_declaration([NotNull] SwiftInterfaceParser.Class_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_name([NotNull] SwiftInterfaceParser.Class_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_name([NotNull] SwiftInterfaceParser.Class_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_body([NotNull] SwiftInterfaceParser.Class_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_body([NotNull] SwiftInterfaceParser.Class_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_member([NotNull] SwiftInterfaceParser.Class_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_member([NotNull] SwiftInterfaceParser.Class_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.final_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinal_clause([NotNull] SwiftInterfaceParser.Final_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.final_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinal_clause([NotNull] SwiftInterfaceParser.Final_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_declaration([NotNull] SwiftInterfaceParser.Protocol_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_declaration([NotNull] SwiftInterfaceParser.Protocol_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_name([NotNull] SwiftInterfaceParser.Protocol_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_name([NotNull] SwiftInterfaceParser.Protocol_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_body([NotNull] SwiftInterfaceParser.Protocol_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_body([NotNull] SwiftInterfaceParser.Protocol_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_member([NotNull] SwiftInterfaceParser.Protocol_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_member([NotNull] SwiftInterfaceParser.Protocol_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_member_declaration([NotNull] SwiftInterfaceParser.Protocol_member_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_member_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_member_declaration([NotNull] SwiftInterfaceParser.Protocol_member_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator_declaration([NotNull] SwiftInterfaceParser.Operator_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator_declaration([NotNull] SwiftInterfaceParser.Operator_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.prefix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefix_operator_declaration([NotNull] SwiftInterfaceParser.Prefix_operator_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.prefix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefix_operator_declaration([NotNull] SwiftInterfaceParser.Prefix_operator_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.postfix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_operator_declaration([NotNull] SwiftInterfaceParser.Postfix_operator_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.postfix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_operator_declaration([NotNull] SwiftInterfaceParser.Postfix_operator_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.infix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfix_operator_declaration([NotNull] SwiftInterfaceParser.Infix_operator_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.infix_operator_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfix_operator_declaration([NotNull] SwiftInterfaceParser.Infix_operator_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.infix_operator_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfix_operator_group([NotNull] SwiftInterfaceParser.Infix_operator_groupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.infix_operator_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfix_operator_group([NotNull] SwiftInterfaceParser.Infix_operator_groupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecedence_group_declaration([NotNull] SwiftInterfaceParser.Precedence_group_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecedence_group_declaration([NotNull] SwiftInterfaceParser.Precedence_group_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecedence_group_attribute([NotNull] SwiftInterfaceParser.Precedence_group_attributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecedence_group_attribute([NotNull] SwiftInterfaceParser.Precedence_group_attributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecedence_group_relation([NotNull] SwiftInterfaceParser.Precedence_group_relationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecedence_group_relation([NotNull] SwiftInterfaceParser.Precedence_group_relationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecedence_group_assignment([NotNull] SwiftInterfaceParser.Precedence_group_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecedence_group_assignment([NotNull] SwiftInterfaceParser.Precedence_group_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_associativity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecedence_group_associativity([NotNull] SwiftInterfaceParser.Precedence_group_associativityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_associativity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecedence_group_associativity([NotNull] SwiftInterfaceParser.Precedence_group_associativityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.associativity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssociativity([NotNull] SwiftInterfaceParser.AssociativityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.associativity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssociativity([NotNull] SwiftInterfaceParser.AssociativityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecedence_group_names([NotNull] SwiftInterfaceParser.Precedence_group_namesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecedence_group_names([NotNull] SwiftInterfaceParser.Precedence_group_namesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecedence_group_name([NotNull] SwiftInterfaceParser.Precedence_group_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.precedence_group_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecedence_group_name([NotNull] SwiftInterfaceParser.Precedence_group_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.extension_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension_declaration([NotNull] SwiftInterfaceParser.Extension_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.extension_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension_declaration([NotNull] SwiftInterfaceParser.Extension_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.extension_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension_body([NotNull] SwiftInterfaceParser.Extension_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.extension_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension_body([NotNull] SwiftInterfaceParser.Extension_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.extension_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension_member([NotNull] SwiftInterfaceParser.Extension_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.extension_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension_member([NotNull] SwiftInterfaceParser.Extension_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.subscript_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_declaration([NotNull] SwiftInterfaceParser.Subscript_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.subscript_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_declaration([NotNull] SwiftInterfaceParser.Subscript_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.subscript_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_head([NotNull] SwiftInterfaceParser.Subscript_headContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.subscript_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_head([NotNull] SwiftInterfaceParser.Subscript_headContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.subscript_result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_result([NotNull] SwiftInterfaceParser.Subscript_resultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.subscript_result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_result([NotNull] SwiftInterfaceParser.Subscript_resultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_associated_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_associated_type_declaration([NotNull] SwiftInterfaceParser.Protocol_associated_type_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_associated_type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_associated_type_declaration([NotNull] SwiftInterfaceParser.Protocol_associated_type_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_declaration([NotNull] SwiftInterfaceParser.Function_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_declaration([NotNull] SwiftInterfaceParser.Function_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_head([NotNull] SwiftInterfaceParser.Function_headContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_head([NotNull] SwiftInterfaceParser.Function_headContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] SwiftInterfaceParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] SwiftInterfaceParser.Function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] SwiftInterfaceParser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] SwiftInterfaceParser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.operator_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator_name([NotNull] SwiftInterfaceParser.Operator_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.operator_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator_name([NotNull] SwiftInterfaceParser.Operator_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_signature([NotNull] SwiftInterfaceParser.Function_signatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_signature([NotNull] SwiftInterfaceParser.Function_signatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.async_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsync_clause([NotNull] SwiftInterfaceParser.Async_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.async_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsync_clause([NotNull] SwiftInterfaceParser.Async_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.throws_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrows_clause([NotNull] SwiftInterfaceParser.Throws_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.throws_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrows_clause([NotNull] SwiftInterfaceParser.Throws_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.rethrows_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRethrows_clause([NotNull] SwiftInterfaceParser.Rethrows_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.rethrows_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRethrows_clause([NotNull] SwiftInterfaceParser.Rethrows_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_result([NotNull] SwiftInterfaceParser.Function_resultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_result([NotNull] SwiftInterfaceParser.Function_resultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.initializer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer_declaration([NotNull] SwiftInterfaceParser.Initializer_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.initializer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer_declaration([NotNull] SwiftInterfaceParser.Initializer_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.initializer_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer_head([NotNull] SwiftInterfaceParser.Initializer_headContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.initializer_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer_head([NotNull] SwiftInterfaceParser.Initializer_headContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.deinitializer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeinitializer_declaration([NotNull] SwiftInterfaceParser.Deinitializer_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.deinitializer_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeinitializer_declaration([NotNull] SwiftInterfaceParser.Deinitializer_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.parameter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_clause([NotNull] SwiftInterfaceParser.Parameter_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.parameter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_clause([NotNull] SwiftInterfaceParser.Parameter_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_list([NotNull] SwiftInterfaceParser.Parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_list([NotNull] SwiftInterfaceParser.Parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] SwiftInterfaceParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] SwiftInterfaceParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.external_parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternal_parameter_name([NotNull] SwiftInterfaceParser.External_parameter_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.external_parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternal_parameter_name([NotNull] SwiftInterfaceParser.External_parameter_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.local_parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_parameter_name([NotNull] SwiftInterfaceParser.Local_parameter_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.local_parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_parameter_name([NotNull] SwiftInterfaceParser.Local_parameter_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.defaultInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultInitializer([NotNull] SwiftInterfaceParser.DefaultInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.defaultInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultInitializer([NotNull] SwiftInterfaceParser.DefaultInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.dyckExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDyckExpression([NotNull] SwiftInterfaceParser.DyckExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.dyckExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDyckExpression([NotNull] SwiftInterfaceParser.DyckExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.dyckSubExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDyckSubExpression([NotNull] SwiftInterfaceParser.DyckSubExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.dyckSubExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDyckSubExpression([NotNull] SwiftInterfaceParser.DyckSubExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.any_other_things_for_dyck_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_other_things_for_dyck_expression([NotNull] SwiftInterfaceParser.Any_other_things_for_dyck_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.any_other_things_for_dyck_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_other_things_for_dyck_expression([NotNull] SwiftInterfaceParser.Any_other_things_for_dyck_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.dotSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotSymbol([NotNull] SwiftInterfaceParser.DotSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.dotSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotSymbol([NotNull] SwiftInterfaceParser.DotSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.declaration_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration_identifier([NotNull] SwiftInterfaceParser.Declaration_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.declaration_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration_identifier([NotNull] SwiftInterfaceParser.Declaration_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.type_inheritance_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_inheritance_clause([NotNull] SwiftInterfaceParser.Type_inheritance_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.type_inheritance_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_inheritance_clause([NotNull] SwiftInterfaceParser.Type_inheritance_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.type_inheritance_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_inheritance_list([NotNull] SwiftInterfaceParser.Type_inheritance_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.type_inheritance_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_inheritance_list([NotNull] SwiftInterfaceParser.Type_inheritance_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.class_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_requirement([NotNull] SwiftInterfaceParser.Class_requirementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.class_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_requirement([NotNull] SwiftInterfaceParser.Class_requirementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] SwiftInterfaceParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] SwiftInterfaceParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.attribute_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_name([NotNull] SwiftInterfaceParser.Attribute_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.attribute_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_name([NotNull] SwiftInterfaceParser.Attribute_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.attribute_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_argument_clause([NotNull] SwiftInterfaceParser.Attribute_argument_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.attribute_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_argument_clause([NotNull] SwiftInterfaceParser.Attribute_argument_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributes([NotNull] SwiftInterfaceParser.AttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributes([NotNull] SwiftInterfaceParser.AttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.balanced_tokens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBalanced_tokens([NotNull] SwiftInterfaceParser.Balanced_tokensContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.balanced_tokens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBalanced_tokens([NotNull] SwiftInterfaceParser.Balanced_tokensContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.balanced_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBalanced_token([NotNull] SwiftInterfaceParser.Balanced_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.balanced_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBalanced_token([NotNull] SwiftInterfaceParser.Balanced_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.any_punctuation_for_balanced_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_punctuation_for_balanced_token([NotNull] SwiftInterfaceParser.Any_punctuation_for_balanced_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.any_punctuation_for_balanced_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_punctuation_for_balanced_token([NotNull] SwiftInterfaceParser.Any_punctuation_for_balanced_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.declaration_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration_modifier([NotNull] SwiftInterfaceParser.Declaration_modifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.declaration_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration_modifier([NotNull] SwiftInterfaceParser.Declaration_modifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.declaration_modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration_modifiers([NotNull] SwiftInterfaceParser.Declaration_modifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.declaration_modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration_modifiers([NotNull] SwiftInterfaceParser.Declaration_modifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.access_level_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccess_level_modifier([NotNull] SwiftInterfaceParser.Access_level_modifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.access_level_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccess_level_modifier([NotNull] SwiftInterfaceParser.Access_level_modifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.mutation_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMutation_modifier([NotNull] SwiftInterfaceParser.Mutation_modifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.mutation_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMutation_modifier([NotNull] SwiftInterfaceParser.Mutation_modifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPattern([NotNull] SwiftInterfaceParser.PatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPattern([NotNull] SwiftInterfaceParser.PatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.wildcard_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWildcard_pattern([NotNull] SwiftInterfaceParser.Wildcard_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.wildcard_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWildcard_pattern([NotNull] SwiftInterfaceParser.Wildcard_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.identifier_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier_pattern([NotNull] SwiftInterfaceParser.Identifier_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.identifier_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier_pattern([NotNull] SwiftInterfaceParser.Identifier_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_type([NotNull] SwiftInterfaceParser.Function_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_type([NotNull] SwiftInterfaceParser.Function_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_type_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_type_argument_clause([NotNull] SwiftInterfaceParser.Function_type_argument_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_type_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_type_argument_clause([NotNull] SwiftInterfaceParser.Function_type_argument_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_type_argument_list([NotNull] SwiftInterfaceParser.Function_type_argument_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_type_argument_list([NotNull] SwiftInterfaceParser.Function_type_argument_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.function_type_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_type_argument([NotNull] SwiftInterfaceParser.Function_type_argumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.function_type_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_type_argument([NotNull] SwiftInterfaceParser.Function_type_argumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.argument_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_label([NotNull] SwiftInterfaceParser.Argument_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.argument_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_label([NotNull] SwiftInterfaceParser.Argument_labelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>dict_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDict_type([NotNull] SwiftInterfaceParser.Dict_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>dict_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDict_type([NotNull] SwiftInterfaceParser.Dict_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>any_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_type([NotNull] SwiftInterfaceParser.Any_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>any_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_type([NotNull] SwiftInterfaceParser.Any_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifier_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier_type([NotNull] SwiftInterfaceParser.Identifier_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifier_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier_type([NotNull] SwiftInterfaceParser.Identifier_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>func_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_type([NotNull] SwiftInterfaceParser.Func_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>func_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_type([NotNull] SwiftInterfaceParser.Func_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>arr_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArr_type([NotNull] SwiftInterfaceParser.Arr_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>arr_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArr_type([NotNull] SwiftInterfaceParser.Arr_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>meta_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeta_type([NotNull] SwiftInterfaceParser.Meta_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>meta_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeta_type([NotNull] SwiftInterfaceParser.Meta_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boxed_protocol_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoxed_protocol_type([NotNull] SwiftInterfaceParser.Boxed_protocol_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boxed_protocol_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoxed_protocol_type([NotNull] SwiftInterfaceParser.Boxed_protocol_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optional_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptional_type([NotNull] SwiftInterfaceParser.Optional_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optional_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptional_type([NotNull] SwiftInterfaceParser.Optional_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>self_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelf_type([NotNull] SwiftInterfaceParser.Self_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>self_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelf_type([NotNull] SwiftInterfaceParser.Self_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unwrapped_optional_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnwrapped_optional_type([NotNull] SwiftInterfaceParser.Unwrapped_optional_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unwrapped_optional_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnwrapped_optional_type([NotNull] SwiftInterfaceParser.Unwrapped_optional_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>proto_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProto_type([NotNull] SwiftInterfaceParser.Proto_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>proto_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProto_type([NotNull] SwiftInterfaceParser.Proto_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>tup_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTup_type([NotNull] SwiftInterfaceParser.Tup_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>tup_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTup_type([NotNull] SwiftInterfaceParser.Tup_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>self_long</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelf_long([NotNull] SwiftInterfaceParser.Self_longContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>self_long</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelf_long([NotNull] SwiftInterfaceParser.Self_longContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>proto_comp_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProto_comp_type([NotNull] SwiftInterfaceParser.Proto_comp_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>proto_comp_type</c>
	/// labeled alternative in <see cref="SwiftInterfaceParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProto_comp_type([NotNull] SwiftInterfaceParser.Proto_comp_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.type_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_annotation([NotNull] SwiftInterfaceParser.Type_annotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.type_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_annotation([NotNull] SwiftInterfaceParser.Type_annotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.any_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_clause([NotNull] SwiftInterfaceParser.Any_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.any_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_clause([NotNull] SwiftInterfaceParser.Any_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.inout_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInout_clause([NotNull] SwiftInterfaceParser.Inout_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.inout_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInout_clause([NotNull] SwiftInterfaceParser.Inout_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.type_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_identifier([NotNull] SwiftInterfaceParser.Type_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.type_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_identifier([NotNull] SwiftInterfaceParser.Type_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] SwiftInterfaceParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] SwiftInterfaceParser.Type_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.tuple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple_type([NotNull] SwiftInterfaceParser.Tuple_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.tuple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple_type([NotNull] SwiftInterfaceParser.Tuple_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.tuple_type_element_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple_type_element_list([NotNull] SwiftInterfaceParser.Tuple_type_element_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.tuple_type_element_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple_type_element_list([NotNull] SwiftInterfaceParser.Tuple_type_element_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.tuple_type_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple_type_element([NotNull] SwiftInterfaceParser.Tuple_type_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.tuple_type_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple_type_element([NotNull] SwiftInterfaceParser.Tuple_type_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.element_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement_name([NotNull] SwiftInterfaceParser.Element_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.element_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement_name([NotNull] SwiftInterfaceParser.Element_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_type([NotNull] SwiftInterfaceParser.Array_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_type([NotNull] SwiftInterfaceParser.Array_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.dictionary_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionary_type([NotNull] SwiftInterfaceParser.Dictionary_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.dictionary_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionary_type([NotNull] SwiftInterfaceParser.Dictionary_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_composition_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_composition_type([NotNull] SwiftInterfaceParser.Protocol_composition_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_composition_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_composition_type([NotNull] SwiftInterfaceParser.Protocol_composition_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.protocol_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProtocol_identifier([NotNull] SwiftInterfaceParser.Protocol_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.protocol_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProtocol_identifier([NotNull] SwiftInterfaceParser.Protocol_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] SwiftInterfaceParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] SwiftInterfaceParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.nil_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNil_literal([NotNull] SwiftInterfaceParser.Nil_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.nil_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNil_literal([NotNull] SwiftInterfaceParser.Nil_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_literal([NotNull] SwiftInterfaceParser.Boolean_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_literal([NotNull] SwiftInterfaceParser.Boolean_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumeric_literal([NotNull] SwiftInterfaceParser.Numeric_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumeric_literal([NotNull] SwiftInterfaceParser.Numeric_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.integer_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger_literal([NotNull] SwiftInterfaceParser.Integer_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.integer_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger_literal([NotNull] SwiftInterfaceParser.Integer_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_literal([NotNull] SwiftInterfaceParser.String_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_literal([NotNull] SwiftInterfaceParser.String_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.label_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel_identifier([NotNull] SwiftInterfaceParser.Label_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.label_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel_identifier([NotNull] SwiftInterfaceParser.Label_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.generic_parameter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_parameter_clause([NotNull] SwiftInterfaceParser.Generic_parameter_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.generic_parameter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_parameter_clause([NotNull] SwiftInterfaceParser.Generic_parameter_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.generic_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_parameter_list([NotNull] SwiftInterfaceParser.Generic_parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.generic_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_parameter_list([NotNull] SwiftInterfaceParser.Generic_parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.generic_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_parameter([NotNull] SwiftInterfaceParser.Generic_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.generic_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_parameter([NotNull] SwiftInterfaceParser.Generic_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.generic_where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_where_clause([NotNull] SwiftInterfaceParser.Generic_where_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.generic_where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_where_clause([NotNull] SwiftInterfaceParser.Generic_where_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.requirement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequirement_list([NotNull] SwiftInterfaceParser.Requirement_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.requirement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequirement_list([NotNull] SwiftInterfaceParser.Requirement_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequirement([NotNull] SwiftInterfaceParser.RequirementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequirement([NotNull] SwiftInterfaceParser.RequirementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.conformance_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConformance_requirement([NotNull] SwiftInterfaceParser.Conformance_requirementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.conformance_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConformance_requirement([NotNull] SwiftInterfaceParser.Conformance_requirementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.same_type_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSame_type_requirement([NotNull] SwiftInterfaceParser.Same_type_requirementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.same_type_requirement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSame_type_requirement([NotNull] SwiftInterfaceParser.Same_type_requirementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.generic_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_argument_clause([NotNull] SwiftInterfaceParser.Generic_argument_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.generic_argument_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_argument_clause([NotNull] SwiftInterfaceParser.Generic_argument_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.generic_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_argument_list([NotNull] SwiftInterfaceParser.Generic_argument_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.generic_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_argument_list([NotNull] SwiftInterfaceParser.Generic_argument_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.generic_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_argument([NotNull] SwiftInterfaceParser.Generic_argumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.generic_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_argument([NotNull] SwiftInterfaceParser.Generic_argumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.opGreater"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpGreater([NotNull] SwiftInterfaceParser.OpGreaterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.opGreater"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpGreater([NotNull] SwiftInterfaceParser.OpGreaterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.arrow_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrow_operator([NotNull] SwiftInterfaceParser.Arrow_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.arrow_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrow_operator([NotNull] SwiftInterfaceParser.Arrow_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.range_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange_operator([NotNull] SwiftInterfaceParser.Range_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.range_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange_operator([NotNull] SwiftInterfaceParser.Range_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.keyword_as_identifier_in_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_as_identifier_in_declarations([NotNull] SwiftInterfaceParser.Keyword_as_identifier_in_declarationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.keyword_as_identifier_in_declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_as_identifier_in_declarations([NotNull] SwiftInterfaceParser.Keyword_as_identifier_in_declarationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.keyword_as_identifier_in_labels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_as_identifier_in_labels([NotNull] SwiftInterfaceParser.Keyword_as_identifier_in_labelsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.keyword_as_identifier_in_labels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_as_identifier_in_labels([NotNull] SwiftInterfaceParser.Keyword_as_identifier_in_labelsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] SwiftInterfaceParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] SwiftInterfaceParser.OperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SwiftInterfaceParser.operator_angles"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator_angles([NotNull] SwiftInterfaceParser.Operator_anglesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SwiftInterfaceParser.operator_angles"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator_angles([NotNull] SwiftInterfaceParser.Operator_anglesContext context);
}
