// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace NativeLibrary
{
    public class Class1
    {
        [UnmanagedCallersOnly(EntryPoint = "add")]
        public static int Add(int a, int b)
        {
            return a + b;
        }

        [UnmanagedCallersOnly(EntryPoint = "write_line")]
        public static int WriteLine(IntPtr pString)
        {
            // The marshalling code is typically auto-generated by a custom tool in larger projects.
            try
            {
                // UnmanagedCallersOnly methods only accept primitive arguments. The primitive arguments
                // have to be marshalled manually if necessary.
                string str = Marshal.PtrToStringAnsi(pString);

                Console.WriteLine(str);
            }
            catch
            {
                // Exceptions escaping out of UnmanagedCallersOnly methods are treated as unhandled exceptions.
                // The errors have to be marshalled manually if necessary.
                return -1;
            }
            return 0;
        }

        [UnmanagedCallersOnly(EntryPoint = "sumstring")]
        public static IntPtr sumstring(IntPtr first, IntPtr second)
        {
            // Parse strings from the passed pointers 
            string my1String = Marshal.PtrToStringAnsi(first);
            string my2String = Marshal.PtrToStringAnsi(second);

            // Concatenate strings 
            string sum = my1String + my2String;

            // Assign pointer of the concatenated string to sumPointer
            IntPtr sumPointer = Marshal.StringToHGlobalAnsi(sum);

            // Return pointer
            return sumPointer;
        }

        [UnmanagedCallersOnly(EntryPoint = "mergestrings")]
        public static void MergeStrings(IntPtr oput, IntPtr strArr, int srcCount,int tgtSize)
        {
            string mainString = String.Empty;
            for (int i = 0; i < srcCount; i++)
            {
                int currentOffset = i * IntPtr.Size;
                IntPtr curPtr = Marshal.ReadIntPtr(strArr, currentOffset);
                string curString = Marshal.PtrToStringAnsi(curPtr);
                mainString += $"String number {i} : {curString} \n";
            }

            //As we are not using Marshal.StringToHGlobalAnsi, we need to manually add the null character
            mainString += '\0';

            // Let's 'send back' our string to the C program
            // We need to convert it to an array of ASCII representations of our characters
            // After that,we'll copy the bytes array to the 'oput' memory location
            byte[] bytesFinalString = Encoding.ASCII.GetBytes(mainString);
            Marshal.Copy(bytesFinalString, 0, oput, mainString.Length > tgtSize-1 ? tgtSize-1 : mainString.Length);
        }

        public struct myStruct
        {
            public IntPtr name;
            public int value;
            public IntPtr secName;
        }

        [UnmanagedCallersOnly(EntryPoint = "popstruct")]
        public static unsafe void PopulateStruct(myStruct* structure)
        {
            structure->name = Marshal.StringToHGlobalAnsi(Guid.NewGuid().ToString());
            structure->value = new Random().Next();
        }
    }
}
