<Project>

  <PropertyGroup>
    <NotSupportedSourceFile>$(IntermediateOutputPath)$(TargetName).notsupported.cs</NotSupportedSourceFile>
    <CoreCompileDependsOn>GenerateNotSupportedSource;$(CoreCompileDependsOn)</CoreCompileDependsOn>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="NotSupported">
      <Value>True</Value>
    </AssemblyMetadata>
  </ItemGroup>

  <!-- GenerateNotSupportedSource
       Inputs:
         * A contract assembly
         * Reference assemblies
       Generates source for the contract that throws PlatformNotSupportedException
  -->
  <Target Name="GenerateNotSupportedSource" 
          DependsOnTargets="ResolveMatchingContract"
          Inputs="@(ReferencePath);@(ResolvedMatchingContract)"
          Outputs="$(NotSupportedSourceFile)">

    <ItemGroup>
      <!-- build out a list of directories where dependencies are located -->
      <_referencePathDirectoriesWithDuplicates Include="@(ReferencePath->'%(RootDir)%(Directory)'->TrimEnd('\'))" />
      <!-- strip metadata, removing duplicates -->
      <_referencePathDirectories Include="%(_referencePathDirectoriesWithDuplicates.Identity)" />
    </ItemGroup>

    <Error Text="No single matching contract found." Condition="'@(ResolvedMatchingContract -> Count())' != '1'" />

    <Microsoft.DotNet.GenAPI.GenAPITask
      Assembly="@(ResolvedMatchingContract)"
      LibPath="@(_referencePathDirectories)"
      OutputPath="$(NotSupportedSourceFile)"
      HeaderFile="$(GeneratePlatformNotSupportedAssemblyHeaderFile)"
      DocIdKinds="$(GenAPIDocIdKinds)"
      ExceptionMessage="$(GeneratePlatformNotSupportedAssemblyMessage)"
      ExcludeApiList="$(GenAPIExcludeApiList)"
      LangVersion="$(LangVersion)" />


    <ItemGroup>
      <FileWrites Include="$(NotSupportedSourceFile)" />
      <Compile Include="$(NotSupportedSourceFile)" />
    </ItemGroup>

  </Target>
</Project>
 