<Project>
  <PropertyGroup>
    <ProducesDotNetReleaseShippingAssets>true</ProducesDotNetReleaseShippingAssets>
    <!-- This avoids creating VS.*.symbols.nupkg packages that are identical to the original package. -->
    <AutoGenerateSymbolPackages>false</AutoGenerateSymbolPackages>
  </PropertyGroup>

  <!-- NativeAOT-LLVM: using the old publishing method from circa https://github.com/dotnet/runtime/pull/108990 -->
  <PropertyGroup>
    <NativeAotLlvmSetVersionForBlobs>true</NativeAotLlvmSetVersionForBlobs>
  </PropertyGroup>
  <ItemGroup>
    <DownloadedArtifactFile Include="$(DownloadDirectory)**" />
    <DownloadedSymbolNupkgFile Include="$(DownloadDirectory)**\*.symbols.nupkg" />
    <DownloadedWixPdbFile Include="$(DownloadDirectory)**\*.wixpdb" />
    <DownloadedWixpackFile Include="$(DownloadDirectory)**\*.wixpack.zip" Condition="'$(PostBuildSign)' != 'true'" />
    <DownloadedWorkloadsVSInsertionFile Include="$(DownloadDirectory)*\workloads-vs\**\*" />
    <DownloadedNupkgFile Include="$(DownloadDirectory)**\*.nupkg" Exclude="@(DownloadedSymbolNupkgFile)" />

    <!-- Exclude symbol packages from have a NuGet signature. These are never pushed to NuGet.org or
          other feeds (in fact, that have identical identity to their non-symbol variant) -->
    <DownloadedSymbolPackagesWithoutPaths Include="@(DownloadedSymbolNupkgFile->'%(Filename)%(Extension)')" />
    <FileSignInfo Include="@(DownloadedSymbolPackagesWithoutPaths->Distinct())" CertificateName="None" />

    <!-- Add files that are not affected by filtering and create checksum for them. -->
    <UploadToBlobStorageFile
      Include="@(DownloadedArtifactFile)"
      Exclude="@(DownloadedSymbolNupkgFile);
                @(DownloadedNupkgFile);
                @(DownloadedWixPdbFile);
                @(DownloadedWorkloadsVSInsertionFile);
                @(DownloadedWixpackFile)" />

    <!--
      Filter out the RID-specific (Runtime) nupkgs and RID-agnostic nupkgs. RID-specific packages
      are published from every job. RID-agnostic nupkgs are built with the same ID/version by
      every job, so one specific job's outputs must be picked to sign and publish.
    -->

    <!-- RID-specific framework packs. -->
    <RuntimeNupkgFile
      Include="
        $(DownloadDirectory)**\Microsoft.*.Runtime.*.nupkg;
        $(DownloadDirectory)**\Microsoft.*.App.Host.*.nupkg;
        $(DownloadDirectory)**\Microsoft.*.App.Crossgen2.*.nupkg"
      Exclude="@(DownloadedSymbolNupkgFile)" />

    <!-- VS insertion packages, carrying RID-specific installers. -->
    <RuntimeNupkgFile
      Include="$(DownloadDirectory)**\VS.Redist.Common.*.nupkg"
      Exclude="@(DownloadedSymbolNupkgFile)" />

    <!--
      Workloads VS insertion artifacts produced by src/workloads/workloads.csproj. Only grab
      the zip artifacts as they're grouped by SDK feature band which correlates with specific VS versions.
    -->
    <WorkloadsVSInsertionFile Include="$(DownloadDirectory)*\workloads-vs\**\*.zip" />

    <!--
      Runtime packages associated with some identity packages. Need to exclude "runtime.native.*"
      because Libraries produces some "runtime.native.Foo" packages with
      "runtime.<rid>.runtime.native.Foo" identity packages.
    -->
    <RuntimeNupkgFile
      Include="$(DownloadDirectory)**\runtime.*.nupkg"
      Exclude="
        $(DownloadDirectory)**\runtime.native.*.nupkg;
        @(DownloadedSymbolNupkgFile)" />

    <!--
      Packages that aren't matched above as RID-specific are considered RID-agnostic. Also include
      the AllConfigurations packages from the Libraries build.
    -->
    <RidAgnosticNupkgToPublishFile
      Include="
        $(DownloadDirectory)**\Microsoft.NET.Sdk.WebAssembly.Pack.*.nupkg;
        $(DownloadDirectory)*\$(PublishRidAgnosticPackagesFromPlatform)\**\*.nupkg;
        $(DownloadDirectory)*\*AllConfigurations\**\*.nupkg"
      Exclude="@(RuntimeNupkgFile);@(DownloadedSymbolNupkgFile)" />

    <TransportPackagesToPublishFile
      Include="$(DownloadDirectory)**\*Transport*.nupkg"
      Exclude="@(RuntimeNupkgFile);@(RidAgnosticNupkgToPublishFile);@(DownloadedSymbolNupkgFile)" />

    <NupkgToPublishFile Include="@(RuntimeNupkgFile);@(RidAgnosticNupkgToPublishFile);@(TransportPackagesToPublishFile)" />

    <!--
      Assuming all symbol packages ship and can be found by turning .nupkg => .symbols.nupkg, find
      them. Don't check for missing symbol packages here: some nupkgs don't have them for valid
      reasons, such as the VS insertion packages that transport MSIs. Symbol package validation
      will check for symbol completeness with file-by-file granularity rather than looking for
      missing symbols.nupkg files: https://github.com/dotnet/arcade/issues/2499.

      Handles several conventions:
      * NonShipping packages have symbol nupkgs that are Shipping.
      * Shipping packages have symbol packages in a "symbols" subdirectory.
    -->
    <PotentialSymbolNupkgToPublishFile
      Include="
        @(NupkgToPublishFile->Replace('\NonShipping\', '\Shipping\')->Replace('.nupkg', '.symbols.nupkg'));
        @(NupkgToPublishFile->Replace('\NonShipping\', '\NonShipping\symbols\')->Replace('.nupkg', '.symbols.nupkg'));
        @(NupkgToPublishFile->Replace('\Shipping\', '\Shipping\symbols\')->Replace('.nupkg', '.symbols.nupkg'))" />

    <SymbolNupkgToPublishFile Include="@(PotentialSymbolNupkgToPublishFile->Distinct()->Exists())" />

    <!-- Packages -->
    <Artifact Include="@(NupkgToPublishFile)"
              IsShipping="$([System.String]::new('%(Identity)').Contains('\Shipping\'))"
              PublishFlatContainer="false"
              Kind="Package" />
    <Artifact Include="@(SymbolNupkgToPublishFile)" PublishFlatContainer="false"
              Kind="Package"/>

    <!-- Blob storage -->
    <Artifact Include="@(UploadToBlobStorageFile)"
              Exclude="@(NupkgToPublishFile);@(SymbolNupkgToPublishFile)"
              IsShipping="$([System.String]::new('%(Identity)').Contains('\Shipping\'))"
              ChecksumPath="%(FullPath).sha512"
              Kind="Blob" />
    <Artifact Include="@(WorkloadsVSInsertionFile)"
              SubBlobFolder="workloads/"
              IsShipping="$([System.String]::new('%(Identity)').Contains('\Shipping\'))"
              Kind="Blob" />
  </ItemGroup>

  <!-- The PGO runtime should always have External visibility, even if someone changes the default artifact visibility -->
  <ItemGroup>
    <Artifact Update="$(ArtifactsNonShippingPackagesDir)dotnet-runtime-pgo-*" Visibility="External" />
  </ItemGroup>

  <!--
    Mark host-RID-targeting assets as Vertical visibility when building in the VMR.
    We can't use NETCoreSdkRuntimeIdentifier here as the Arcade SDK projects don't import the .NET SDK.
    Instead, just make sure we include the assets targeting "not the output rid", which will catch the host assets.
  -->
  <ItemGroup Condition="'$(EnableDefaultRidSpecificArtifacts)' != 'true' and '$(DotNetBuildFromVMR)' == 'true'">
    <_HostArtifact Include="$(ArtifactsPackagesDir)**\runtime.*.Microsoft.NETCore.ILAsm.*.nupkg"
                    Exclude="$(ArtifactsPackagesDir)**\runtime.$(TargetRid).Microsoft.NETCore.ILAsm.*.nupkg" />

    <_HostArtifact Include="$(ArtifactsPackagesDir)**\runtime.*.Microsoft.NETCore.ILDAsm.*.nupkg"
                    Exclude="$(ArtifactsPackagesDir)**\runtime.$(TargetRid).Microsoft.NETCore.ILDAsm.*.nupkg" />

    <_HostArtifact Include="$(ArtifactsPackagesDir)**\runtime.*.Microsoft.DotNet.ILCompiler.*.nupkg"
                    Exclude="$(ArtifactsPackagesDir)**\runtime.$(TargetRid).Microsoft.DotNet.ILCompiler.*.nupkg" />

    <_HostArtifact Include="$(ArtifactsPackagesDir)**\Microsoft.NETCore.App.Crossgen2.*.nupkg"
                    Exclude="$(ArtifactsPackagesDir)**\Microsoft.NETCore.App.Crossgen2.$(TargetRid).*.nupkg" />

    <Artifact Update="@(_HostArtifact)"
              Visibility="Vertical"
              IsShipping="false" />
  </ItemGroup>

  <Target Name="GetNonStableProductVersion">
    <!-- Retrieve the non-stable runtime pack product version.
         Don't stabilize the package version in order to retrieve the VersionSuffix. -->
    <MSBuild Projects="$(RepoRoot)src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.CoreCLR.sfxproj"
             Targets="ReturnProductVersion"
             Properties="IsShipping=false;
                         Crossgen2SdkOverridePropsPath=;
                         Crossgen2SdkOverrideTargetsPath=">
      <Output TaskParameter="TargetOutputs" PropertyName="NonStableProductVersion" />
    </MSBuild>
  </Target>

  <!--
    Only generate the productVersion.txt and runtime-productVersion.txt files when we're building
    either the full VMR repo or not building in the VMR infrastructure.
    This ensures that we don't produce these files in the "Repo source build" builds,
    but we do produce them in both the VMR and the runtime official build.
  -->
  <PropertyGroup Condition="'$(DotNetBuildFromVMR)' == 'true'">
    <ShouldGenerateProductVersionFiles Condition="'$(TargetRid)' == 'win-x64' and ('$(DotNetBuildPass)' == '' or '$(DotNetBuildPass)' == '1')">true</ShouldGenerateProductVersionFiles>
    <ShouldGenerateProductVersionFiles Condition="'$(DotNetBuildSourceOnly)' == 'true'">true</ShouldGenerateProductVersionFiles>
  </PropertyGroup>

  <Target Name="GenerateProductVersionFiles"
          DependsOnTargets="GetNonStableProductVersion"
          BeforeTargets="PublishToAzureDevOpsArtifacts"
          Condition="'$(ShouldGenerateProductVersionFiles)' == 'true'">
    <!-- Retrieve the runtime pack product version. -->
    <MSBuild Projects="$(RepoRoot)src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.CoreCLR.sfxproj"
             Targets="ReturnProductVersion"
             Properties="Crossgen2SdkOverridePropsPath=;
                         Crossgen2SdkOverrideTargetsPath=">
      <Output TaskParameter="TargetOutputs" PropertyName="ProductVersionForVersionsFile" />
    </MSBuild>

    <ItemGroup>
      <ProductVersionFile Include="$(ArtifactsShippingPackagesDir)productVersion.txt" />
      <ProductVersionFile Include="$(ArtifactsShippingPackagesDir)runtime-productVersion.txt" />
    </ItemGroup>

    <!-- Generate productVersion.txt file containing the product version. -->
    <WriteLinesToFile File="%(ProductVersionFile.Identity)"
                      Lines="$(ProductVersionForVersionsFile)"
                      Overwrite="true"
                      Encoding="ASCII" />

    <ItemGroup>
      <Artifact Include="@(ProductVersionFile)"
                RelativeBlobPath="Runtime/$(NonStableProductVersion)/%(Filename)%(Extension)" />
    </ItemGroup>
  </Target>

  <Target Name="AddRelativeBlobPathToInstallerArtifacts"
          DependsOnTargets="GetNonStableProductVersion"
          BeforeTargets="PublishToAzureDevOpsArtifacts"
          AfterTargets="GenerateChecksumsFromArtifacts">
    <ItemGroup Condition="'$(DotNetBuildFromVMR)' == 'true' or '$(NativeAotLlvmSetVersionForBlobs)' == 'true'">
      <Artifact Condition="'%(Artifact.Kind)' != 'Package' and '%(Artifact.RelativeBlobPath)' == ''"
                RelativeBlobPath="Runtime/$(NonStableProductVersion)/%(Artifact.SubBlobFolder)%(Filename)%(Extension)" />
    </ItemGroup>
    <!-- In vertical dotnet/runtime legs outside of the VMR, set the "relative blob path" to shipping vs non-shipping to make our download/upload work. -->
    <ItemGroup Condition="'$(DotNetBuildFromVMR)' != 'true' and '$(NativeAotLlvmSetVersionForBlobs)' != 'true'">
      <Artifact Condition="'%(Artifact.Kind)' == 'Blob' and '%(Artifact.IsShipping)' == 'true'"
                RelativeBlobPath="packages/$(Configuration)/Shipping/%(Filename)%(Extension)" />
      <Artifact Condition="'%(Artifact.Kind)' == 'Blob' and '%(Artifact.IsShipping)' != 'true'"
                RelativeBlobPath="packages/$(Configuration)/NonShipping/%(Filename)%(Extension)" />
      <ItemsToPushToBlobFeed Condition="'%(ItemsToPushToBlobFeed.Kind)' == 'Blob' and '%(ItemsToPushToBlobFeed.IsShipping)' == 'true'"
                             RelativeBlobPath="packages/$(Configuration)/Shipping/%(Filename)%(Extension)" />
      <ItemsToPushToBlobFeed Condition="'%(ItemsToPushToBlobFeed.Kind)' == 'Blob' and '%(ItemsToPushToBlobFeed.IsShipping)' != 'true'"
                             RelativeBlobPath="packages/$(Configuration)/NonShipping/%(Filename)%(Extension)" />

      <Artifact Condition="'%(Artifact.IsVSSetup)' == 'true'"
                RelativeBlobPath="VSSetup/%(Filename)%(Extension)" />
    </ItemGroup>
  </Target>
</Project>
