parameters:
  campaignId: ''
  cohortId: ''
  aspNetValidationBinding: ''

jobs:
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: release
    runtimeFlavor: coreclr
    platforms:
    - android_arm64
    jobParameters:
      templatePath: templates-official
      isOfficialBuild: true
      enableSigning: false
      buildArgs: -s clr.runtime+clr.alljits+clr.corelib+clr.nativecorelib+clr.tools+clr.packages+libs -c $(_BuildConfig)
      nameSuffix: AndroidCoreCLR
      timeoutInMinutes: 240
      templateContext:
        outputs:
        - output: pipelineArtifact
          displayName: Publish Android CoreCLR JIT archive
          targetPath: $(Build.StagingDirectory)/AndroidHelloWorldArm64CoreCLR.tar.gz
          artifactName: AndroidHelloWorldArm64CoreCLR
        - output: pipelineArtifact
          displayName: Publish Android CoreCLR static archive
          targetPath: $(Build.StagingDirectory)/AndroidHelloWorldArm64CoreCLRStaticLinking.tar.gz
          artifactName: AndroidHelloWorldArm64CoreCLRStaticLinking
        - output: pipelineArtifact
          displayName: Publish Android CoreCLR R2R archive
          targetPath: $(Build.StagingDirectory)/AndroidHelloWorldArm64CoreCLRR2R.tar.gz
          artifactName: AndroidHelloWorldArm64CoreCLRR2R
      postBuildSteps:
      - template: /eng/pipelines/performance/templates/build-perf-sample-apps.yml
        parameters:
          runtimeType: coreclr
          isOfficialBuild: true
          publishArtifacts: false

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: release
    runtimeFlavor: coreclr
    platforms:
    - ios_arm64
    jobParameters:
      templatePath: templates-official
      isOfficialBuild: true
      enableSigning: false
      buildArgs: -s clr+clr.runtime+libs+packs -c $(_BuildConfig)
      nameSuffix: iOSCoreCLR
      timeoutInMinutes: 240
      templateContext:
        outputs:
        - output: pipelineArtifact
          displayName: Publish iOS CoreCLR interpreter archive
          targetPath: $(Build.StagingDirectory)/iOSSampleAppCoreCLRInterpreterNoSymbols.zip
          artifactName: iOSSampleAppCoreCLRInterpreterNoSymbols
        - output: pipelineArtifact
          displayName: Publish iOS CoreCLR R2R archive
          targetPath: $(Build.StagingDirectory)/iOSSampleAppCoreCLRR2RNoSymbols.zip
          artifactName: iOSSampleAppCoreCLRR2RNoSymbols
      postBuildSteps:
      - template: /eng/pipelines/performance/templates/build-perf-sample-apps.yml
        parameters:
          runtimeType: coreclr
          isOfficialBuild: true
          publishArtifacts: false

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: Release
    runtimeFlavor: coreclr
    platforms:
    - browser_wasm
    jobParameters:
      templatePath: templates-official
      isOfficialBuild: true
      enableSigning: false
      buildArgs: -s clr+libs+host+packs -c $(_BuildConfig) /p:AotHostArchitecture=x64 /p:AotHostOS=$(_hostedOS) /p:BuildHostTools=true /p:CrossBuildHostTools=true
      nameSuffix: wasm_coreclr
      timeoutInMinutes: 240
      templateContext:
        outputs:
        - output: pipelineArtifact
          displayName: Publish Browser WASM CoreCLR archive
          targetPath: $(Build.StagingDirectory)/BrowserWasmCoreCLR.tar.gz
          artifactName: BrowserWasmCoreCLR
        - output: pipelineArtifact
          displayName: Publish Browser WASM CoreCLR workload packages
          targetPath: $(Build.SourcesDirectory)/artifacts/staging-coreclr-workload-packages
          artifactName: BrowserWasmCoreCLRWorkloadPackages_$(_hostedOs)
      postBuildSteps:
      - template: /eng/pipelines/performance/templates/perf-wasm-prepare-artifacts-steps.yml
        parameters:
          configForBuild: Release
          artifactName: BrowserWasmCoreCLR
          sdkDirName: dotnet-none
          includeRefPack: false
          includeCoreClrToolchainPacks: true
          publishCoreClrWorkloadPackages: true
          isOfficialBuild: true
          publishArtifacts: false

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: release
    runtimeFlavor: coreclr
    platforms:
    - linux_arm64
    jobParameters:
      templatePath: templates-official
      isOfficialBuild: true
      enableSigning: false
      buildArgs: -s clr+libs+packs -c $(_BuildConfig) -dynamiccodecompiled false
      nameSuffix: coreclr_r2r_interpreter
      timeoutInMinutes: 240
      templateContext:
        outputs:
        - output: pipelineArtifact
          displayName: Publish CoreCLR R2R interpreter archive
          targetPath: $(Build.StagingDirectory)/BuildArtifacts_$(osGroup)$(osSubgroup)_$(archType)_$(_BuildConfig)_coreclr_r2r_interpreter$(archiveExtension)
          artifactName: BuildArtifacts_$(osGroup)$(osSubgroup)_$(archType)_$(_BuildConfig)_coreclr_r2r_interpreter
      postBuildSteps:
      - template: /eng/pipelines/common/upload-artifact-step.yml
        parameters:
          rootFolder: $(Build.SourcesDirectory)/artifacts/bin
          includeRootFolder: false
          archiveType: $(archiveType)
          archiveExtension: $(archiveExtension)
          tarCompression: $(tarCompression)
          artifactName: BuildArtifacts_$(osGroup)$(osSubgroup)_$(archType)_$(_BuildConfig)_coreclr_r2r_interpreter
          displayName: CoreCLR R2R interpreter build assets
          isOfficialBuild: true
          publishArtifact: false
