# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
trigger:
  batch: true
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT
pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT
variables:
- template: /eng/pipelines/common/variables.yml@self
- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - name: TeamName
    value: dotnet-core
extends:
  template: /eng/pipelines/common/templates/pipeline-with-resources.yml@self
  parameters:
    stages:
    - stage: Build
      jobs:
      - ${{ if ne(variables.isOfficialBuild, true) }}:
        - template: /eng/pipelines/common/platform-matrix.yml
          parameters:
            jobTemplate: /eng/pipelines/common/global-build-job.yml
            buildConfig: Debug
            platforms:
            - windows_x64
            - OSX_x64
            - Browser_wasm_win
            - wasi_wasm_win
            jobParameters:
              timeoutInMinutes: 300
              testGroup: innerloop
              buildArgs: -s clr.aot+libs+nativeaot.packages -lc Release -rc Debug
              postBuildSteps:
              - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                parameters:
                  librariesConfiguration: Release
      - ${{ if ne(variables.isOfficialBuild, true) }}:
        - template: /eng/pipelines/common/platform-matrix.yml
          parameters:
            jobTemplate: /eng/pipelines/common/global-build-job.yml
            buildConfig: Checked
            platforms:
            - windows_x64
            jobParameters:
              timeoutInMinutes: 100
              testGroup: innerloop
              buildArgs: -s clr+libs+host+packs -c debug -runtimeConfiguration Checked
              postBuildSteps:
              - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                parameters:
                  uploadRuntimeTests: true
                  librariesConfiguration: Debug
      - template: /eng/pipelines/common/platform-matrix.yml
        parameters:
          jobTemplate: /eng/pipelines/common/global-build-job.yml
          buildConfig: Release
          platforms:
          - windows_arm64
          - OSX_x64
          - Browser_wasm_win
          - wasi_wasm_win
          jobParameters:
            timeoutInMinutes: 300
            isOfficialBuild: ${{ variables.isOfficialBuild }}
            testGroup: innerloop
            postBuildSteps:
            - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
              parameters:
                isOfficialBuild: ${{ variables.isOfficialBuild }}
                uploadLibrariesTests: ${{ eq(variables.isOfficialBuild, false) }}
                uploadIntermediateArtifacts: ${{ variables.isOfficialBuild }}
                librariesConfiguration: Release
            ${{ if eq(variables.isOfficialBuild, false) }}:
              buildArgs: -s clr.aot+libs+nativeaot.packages -c $(_BuildConfig) /p:ArchiveTests=true
            ${{ if eq(variables.isOfficialBuild, true) }}:
              buildArgs: -s clr.aot+libs+nativeaot.packages -c $(_BuildConfig)
    - ${{ if eq(variables.isOfficialBuild, true) }}:
      - template: /eng/pipelines/official/stages/publish.yml
        parameters:
          isOfficialBuild: ${{ variables.isOfficialBuild }}
resources: {}