# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: Windows_NT
      archType: x64
      pool:
        vmImage: 'windows-latest'

  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: OSX
      archType: x64
      pool:
        vmImage: 'macOS-latest'

  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: Linux
      archType: x64
      pool:
        vmImage: 'ubuntu-latest'
