# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    - name: TeamName
      value: dotnet-core

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:

        #
        # Build and test with Debug libraries and Debug runtime
        #
        - template: /eng/pipelines/common/platform-matrix.yml
          parameters:
            jobTemplate: /eng/pipelines/common/global-build-job.yml
            helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
            buildConfig: debug
            platforms:
            # - osx_x64 # Upstream break.
            - windows_x64
            - Browser_wasm_win
            - wasi_wasm_win
            # Use a different name to differentiate from upstream as we need the -sanitizer image to get build tools that are not present in the stock wasi-wasm image.
            - Browser_wasm_linux_x64_naot_llvm
            - wasi_wasm_linux_x64_naot_llvm
            jobParameters:
              timeoutInMinutes: 300
              buildArgs: -s clr.aot+libs+nativeaot.packages -c debug -rc $(_BuildConfig)
              postBuildSteps:
                - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                  parameters:
                    librariesConfiguration: Debug

        #
        # Build and test with Debug libraries and Checked runtime
        #
        - template: /eng/pipelines/common/platform-matrix.yml
          parameters:
            jobTemplate: /eng/pipelines/common/global-build-job.yml
            helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
            buildConfig: checked
            platforms:
            - windows_x64
            jobParameters:
              timeoutInMinutes: 300
              buildArgs: -s clr.aot+libs+nativeaot.packages -c debug -rc $(_BuildConfig)
              postBuildSteps:
                - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                  parameters:
                    uploadRuntimeTests: true
                    librariesConfiguration: Debug

        #
        # Build and test with Release libraries and Release runtime
        #
        - template: /eng/pipelines/common/platform-matrix.yml
          parameters:
            jobTemplate: /eng/pipelines/common/global-build-job.yml
            helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
            buildConfig: release
            ${{ if containsValue(parameters.platforms, 'Browser_wasm_linux_x64_naot_llvm') }}:
              container: azurelinux-3.0-cross-amd64-net9.0-sanitizer
            platforms:
            - linux_x64
            - osx_x64
            - windows_x64
            - Browser_wasm_win
            - wasi_wasm_win
            # Use a different name to differentiate from upstream as we need the -sanitizer image to get build tools that are not present in the stock wasi-wasm image.
            - wasi_wasm_linux_x64_naot_llvm
            - Browser_wasm_linux_x64_naot_llvm
            jobParameters:
              timeoutInMinutes: 300
              buildArgs: -s clr.aot+libs+nativeaot.packages -c $(_BuildConfig) /p:ArchiveTests=true
              postBuildSteps:
                - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                  parameters:
                    librariesConfiguration: Release
