trigger:
  batch: true
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT

variables:
- template: /eng/pipelines/common/variables.yml
  parameters:
    templatePath: 'templates-official'

- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - name: TeamName
    value: dotnet-core
extends:
  template: /eng/pipelines/common/templates/pipeline-with-resources.yml@self
  parameters:
    isOfficialBuild: true
    stages:
    - stage: Build
      jobs:
      - template: /eng/pipelines/common/platform-matrix.yml
        parameters:
          jobTemplate: /eng/pipelines/common/global-build-job.yml
          buildConfig: Release
          container: azurelinux-3.0-cross-amd64-net9.0-sanitizer
          platforms:
          - Browser_wasm_win
          - wasi_wasm_win
          - Browser_wasm_linux_x64
          - wasi_wasm_linux_x64
          jobParameters:
            templatePath: 'templates-official'
            timeoutInMinutes: 300
            isOfficialBuild: true
            testGroup: innerloop
            buildArgs: -s clr.aot+libs+nativeaot.packages -c $(_BuildConfig)
            postBuildSteps:
            - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
              parameters:
                isOfficialBuild: true
                uploadIntermediateArtifacts: true
                librariesConfiguration: Release
    - template: /eng/pipelines/official/stages/publish.yml
      parameters:
        isOfficialBuild: true
