# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - name: _TeamName
    value: dotnet-core

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/pipelines/templates/build-job.yml
    parameters:
      osGroup: OSX
      archType: x64
      # ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        # isOfficialBuild: true
      runTests: true
      pool:
        vmImage: 'macOS-latest'

# Publish and validation steps. Only run in official builds
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: \eng\common\templates\post-build\post-build.yml
    parameters:
      publishingInfraVersion: 3
      validateDependsOn:
        - build
      enableSourceLinkValidation: true
