# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    exclude:
    - '**.md'
    - eng/Version.Details.xml
    - .devcontainer/*
    - .github/*
    - docs/*
    - LICENSE.TXT
    - PATENTS.TXT
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    - name: TeamName
      value: dotnet-core

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:

        - ${{ if ne(variables.isOfficialBuild, true) }}:
          #
          # Build and test with Debug libraries and Debug runtime
          #
          - template: /eng/pipelines/common/platform-matrix.yml
            parameters:
              jobTemplate: /eng/pipelines/common/global-build-job.yml
              helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
              buildConfig: debug
              platforms:
#              - linux_x64
              - osx_x64
              - windows_x64
              - Browser_wasm_win
              - wasi_wasm_win
              jobParameters:
                timeoutInMinutes: 300
                buildArgs: -s clr.aot+libs+nativeaot.packages -c debug -rc $(_BuildConfig)
                postBuildSteps:
                  - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                    parameters:
                      librariesConfiguration: Debug

          #
          # Build and test with Debug libraries and Checked runtime
          #
          - template: /eng/pipelines/common/platform-matrix.yml
            parameters:
              jobTemplate: /eng/pipelines/common/global-build-job.yml
              helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
              buildConfig: checked
              platforms:
#              - linux_x64
              - windows_x64
              jobParameters:
                timeoutInMinutes: 300
                buildArgs: -s clr.aot+libs+nativeaot.packages -c debug -rc $(_BuildConfig)
                postBuildSteps:
                  - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                    parameters:
                      uploadRuntimeTests: true
                      librariesConfiguration: Debug

          #
          # Build and test with Release libraries and Release runtime
          #
          - template: /eng/pipelines/common/platform-matrix.yml
            parameters:
              jobTemplate: /eng/pipelines/common/global-build-job.yml
              helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
              buildConfig: release
              platforms:
#              - linux_x64
              - osx_x64
              - windows_x64
              - Browser_wasm_win
              - wasi_wasm_win
              jobParameters:
                timeoutInMinutes: 300
                buildArgs: -s  clr.aot+libs+nativeaot.packages -c $(_BuildConfig) /p:ArchiveTests=true
                postBuildSteps:
                  - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                    parameters:
                      librariesConfiguration: Release

        - ${{ else }}:
          #
          # Build the whole product with Release CoreCLR
          #
          - template: /eng/pipelines/common/platform-matrix.yml
            parameters:
              jobTemplate: /eng/pipelines/common/global-build-job.yml
              helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
              buildConfig: release
              platforms:
#              - linux_x64
              - windows_x64
              jobParameters:
                isOfficialBuild: true
                timeoutInMinutes: 380
                buildArgs: -s clr+libs+hosts+packs -c $(_BuildConfig)
                postBuildSteps:
                  - template: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml
                    parameters:
                      isOfficialBuild: true
                      uploadIntermediateArtifacts: true
                      librariesConfiguration: Release

    - ${{ if eq(variables.isOfficialBuild, true) }}:
      - template: /eng/pipelines/official/stages/publish.yml
        parameters:
          isOfficialBuild: true
