# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - name: _TeamName
    value: dotnet-core
stages:
- stage: build
  displayName: Build
  jobs:
  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/pipelines/common/templates/build-job.yml
      parameters:
        osGroup: OSX
        archType: arm64
        runTests: true
        pool:
          vmImage: 'macOS-latest'

    - template: /eng/pipelines/common/templates/build-job.yml
      parameters:
        osGroup: OSX
        archType: x64
        runTests: true
        pool:
          vmImage: 'macOS-latest'
