# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

stages:
- stage: Build
  jobs:

  #
  # Build on Debug configuration
  #
  - template: /eng/pipelines/templates/platform-matrix.yml
    parameters:
      jobTemplate: /eng/pipelines/templates/build-job.yml
      buildConfig: Debug
      platforms:
      - Linux_x64
      - Windows_NT_x64
      - OSX_x64
      jobParameters:
        isOfficialBuild: ${{ variables.isOfficialBuild }}

  #
  # Build on Release configuration
  #
  - template: /eng/pipelines/templates/platform-matrix.yml
    parameters:
      jobTemplate: /eng/pipelines/templates/build-job.yml
      buildConfig: Release
      platforms:
      - Linux_x64
      - Windows_NT_x64
      - OSX_x64
      jobParameters:
        isOfficialBuild: ${{ variables.isOfficialBuild }}
