# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - feature/*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    - name: TeamName
      value: dotnet-core

stages:
- stage: Build
  jobs:
  #
  # Checkout repository
  #
  - template: /eng/pipelines/common/checkout-job.yml

  #
  # Build the whole product using Mono and run libraries tests
  #
  - template: /eng/pipelines/common/platform-matrix.yml
    parameters:
      jobTemplate: /eng/pipelines/common/global-build-job.yml
      helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
      buildConfig: Release
      runtimeFlavor: mono
      platforms:
      - Linux_s390x
      jobParameters:
        testGroup: innerloop
        nameSuffix: AllSubsets_Mono
        buildArgs: -s mono+libs+installer+libs.tests -c $(_BuildConfig) /p:ArchiveTests=true
        timeoutInMinutes: 120
        # extra steps, run tests
        extraStepsTemplate: /eng/pipelines/libraries/helix.yml
        extraStepsParameters:
          creator: dotnet-bot
          testRunNamePrefixSuffix: Mono_$(_BuildConfig)

- ${{ if eq(variables.isOfficialBuild, true) }}:
  - template: /eng/pipelines/official/stages/publish.yml
    parameters:
      isOfficialBuild: ${{ variables.isOfficialBuild }}
