#ifndef _MONOSHIM_UTILS_MONO_MEMORY_MODEL_H
#define _MONOSHIM_UTILS_MONO_MEMORY_MDOEL_H

enum {
    MONO_MEMORY_BARRIER_NONE = 0,
    MONO_MEMORY_BARRIER_ACQ = 1,
    MONO_MEMORY_BARRIER_REL = 2,
    MONO_MEMORY_BARRIER_SEQ = 3,
};


#endif /*_MONOSHIM_UTILS_MONO_MEMORY_MDOEL_H*/
