parameters:
  variables: {}
  osGroup: ''
  platform: ''
  archType: ''
  container: ''
  pool: {}
  isOfficialBuild: false
  runTests: true
  scriptArgs: ''

jobs:

- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    enableTelemetry: true
    helixRepo: dotnet/runtimelab
    pool: ${{ parameters.pool }}
    enableMicrobuild: true
    graphFileGeneration:
      enabled: false
      includeToolset: false

    jobs:
    - job: ${{ format('{0}_{1}', parameters.osGroup, parameters.archType) }}
      displayName: ${{ format('{0} {1}', parameters.osGroup, parameters.archType) }}
      strategy:
        matrix:
          Release:
            _BuildConfig: Release
          ${{ if eq(parameters.isOfficialBuild, false) }}:
            Debug:
              _BuildConfig: Debug

      ${{ if eq(parameters.runTests, true) }}:
        testResultsFormat: vstest
        testRunTitle: ${{ parameters.osGroup }}_${{ parameters.archType }}_$(_BuildConfig)

      variables:
        - _buildScript: ./build.sh
        - _generateScript: ./generate.sh
        - _dotnetScript: ./dotnet.sh

        - _testBuildArg: ''
        - ${{ if eq(parameters.runTests, true) }}:
          - _testBuildArg: -test

      steps:
      - script: $(_buildScript)
                -pack
                -c $(_BuildConfig)
                $(_testBuildArg)
                /p:TargetPlatform=${{ parameters.archType }}
        displayName: Build and test

      - script: $(_dotnetScript) format --exclude artifacts --verify-no-changes --verbosity detailed
        displayName: Verify code formatting

      - ${{ if and(ne(parameters.isOfficialBuild, true), eq(parameters.platform, 'maccatalyst')) }}:
        - script: |
            $(_generateScript) --configuration $(_BuildConfig) --platform MacCatalyst ${{ parameters.scriptArgs }}
            $(_buildScript) -ci -publish -pack -configuration Release --projects $(pwd)/artifacts/MacCatalyst/Swift.Bindings.MacCatalyst.Experimental.csproj
          displayName: Generate MacCatalyst bindings

        - script: |
            $(_dotnetScript) workload install maui maccatalyst mobile-librarybuilder-net9 --version 10.0.100-preview.1.25124.2 --source https://api.nuget.org/v3/index.json
            $(_dotnetScript) new tool-manifest && $(_dotnetScript) tool install microsoft.dotnet.xharness.cli --version "10.0.0-prerelease*"
            sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          displayName: Install dependencies

        - script: |
            $(_dotnetScript) build ./src/Swift.Bindings/tests/FrameworkTests/Swift.Bindings.Framework.Tests.csproj \
            -f net10.0-${{ parameters.platform }} \
            -c $(_BuildConfig) \
            -r ${{ parameters.platform }}-${{ parameters.archType }} \
            /p:UseMaui=true
          displayName: Build device tests

        - script: |
            $(_dotnetScript) xharness apple test \
            --target ${{ parameters.platform }} \
            --timeout="00:02:00" \
            --launch-timeout=00:06:00 \
            --app ./src/Swift.Bindings/tests/FrameworkTests/bin/$(_BuildConfig)/net10.0-${{ parameters.platform }}/${{ parameters.platform }}-${{ parameters.archType }}/Swift.Bindings.Framework.Tests.app \
            --output-directory artifacts
          displayName: Run device tests

      - ${{ if eq(parameters.isOfficialBuild, true) }}:
        - template: /eng/pipelines/common/upload-intermediate-artifacts-step.yml
          parameters:
            name: ${{ parameters.osGroup }}${{ parameters.archType }}
            isOfficialBuild: ${{ parameters.isOfficialBuild }}
