parameters:
  variables: {}
  osGroup: ''
  platform: ''
  archType: ''
  container: ''
  pool: {}

jobs:

- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    enableTelemetry: true
    helixRepo: dotnet/runtimelab
    pool: ${{ parameters.pool }}
    enableMicrobuild: true
    graphFileGeneration:
      enabled: false
      includeToolset: false

    jobs:
    - job: ${{ format('{0}_{1}_{2}', parameters.osGroup, parameters.platform, parameters.archType) }}
      displayName: ${{ format('{0} {1} {2}', parameters.osGroup, parameters.platform, parameters.archType) }}
      strategy:
        matrix:
          Release:
            _BuildConfig: Release
          Debug:
            _BuildConfig: Debug

      steps:
      # Use .NET 9 as MAUI workloads are not available for the default SDK
      - script: |
          cat << 'EOF' > global.json
          {
            "sdk": {
              "version": "9.0.102",
              "allowPrerelease": true,
              "rollForward": "major"
            },
            "tools": {
              "dotnet": "9.0.102",
              "runtimes": {
                "dotnet": [
                  "$(MicrosoftNETCoreAppVersion)"
                ]
              }
            },
            "msbuild-sdks": {
              "Microsoft.DotNet.Arcade.Sdk": "10.0.0-beta.24515.3"
            }
          }
          EOF
          ./build.sh
          ./dotnet.sh workload install maui maccatalyst --version 9.0.103 --source https://api.nuget.org/v3/index.json
          ./dotnet.sh new tool-manifest && ./dotnet.sh tool install microsoft.dotnet.xharness.cli --version "9.0.0-prerelease*"
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
        displayName: Install dependencies

      - script: |
          ./dotnet.sh build ./src/Swift.Bindings/tests/FrameworkTests/Swift.Bindings.Framework.Tests.csproj \
          -f net9.0-${{ parameters.platform }} \
          -c $(_BuildConfig) \
          -r ${{ parameters.platform }}-${{ parameters.archType }} \
          /p:UseMaui=true
        displayName: Publish app

      - script: |
          ./dotnet.sh xharness apple test \
          --target ${{ parameters.platform }} \
          --timeout="00:02:00" \
          --launch-timeout=00:06:00 \
          --app ./src/Swift.Bindings/tests/FrameworkTests/bin/$(_BuildConfig)/net9.0-${{ parameters.platform }}/${{ parameters.platform }}-${{ parameters.archType }}/Swift.Bindings.Framework.Tests.app \
          --output-directory artifacts
        displayName: Run device tests

      - script: |
          cat artifacts/Swift.Bindings.Framework.Tests.log
        displayName: Display logs
